#!/bin/bash

# versions from build.gradle
export ANDROID_PLATFORM=$(sed -n '6p' etopan-app/app/build.gradle | grep -oE "[^ ]+$")
export BUILDTOOLS_VERSION=$(sed -n '7p' etopan-app/app/build.gradle | grep -oE "[^ ]+$" | sed 's/"//g')
export NDK_VERSION=$(sed -n '8p' etopan-app/app/build.gradle | grep -oE "[^ ]+$" | sed 's/"//g')

# versions
export BUNDLETOOL_VERSION=1.15.6
export MINIFY_VERSION=v2.20.6

if [ $# -eq 0 ]; then
  return
elif [ $1 == "ANDROID_PLATFORM" ]; then
  echo "$ANDROID_PLATFORM"
elif [ $1 == "BUILDTOOLS_VERSION" ]; then
  echo "$BUILDTOOLS_VERSION"
elif [ $1 == "NDK_VERSION" ]; then
  echo "$NDK_VERSION"
elif [ $1 == "BUNDLETOOL_VERSION" ]; then
  echo "$BUNDLETOOL_VERSION"
elif [ $1 == "MINIFY_VERSION" ]; then
  echo "$MINIFY_VERSION"
fi
