#!/bin/bash

OUT=target/build
mkdir -p $OUT
if [ "$#" -ne 1 ]; then
  echo "./build api|android|web|full"
elif [ $1 == "api" ]; then
  rm -f $OUT/etopa
  cross build -p etopai --release --target x86_64-unknown-linux-musl
  strip target/x86_64-unknown-linux-musl/release/etopai && cp target/x86_64-unknown-linux-musl/release/etopai $OUT/etopa
elif [ $1 == "android" ]; then
  rm -f $OUT/etopa.aab && rm -f $OUT/etopa.apk
  ./build web
  JNI_LIBS=etopan-app/app/src/main/jniLibs
  if ! [[ "$PATH" == ?(*:)"$HOME/.android/ndk/arm64/bin"?(:*) ]]; then
    export PATH="$PATH:$HOME/.android/ndk/arm64/bin"
  fi
  if ! [[ "$PATH" == ?(*:)"$HOME/.android/ndk/arm/bin"?(:*) ]]; then
    export PATH="$PATH:$HOME/.android/ndk/arm/bin"
  fi
  cross build -p etopan --release --target aarch64-linux-android
  cross build -p etopan --release --target armv7-linux-androideabi
  rm -rf $JNI_LIBS && mkdir -p $JNI_LIBS/arm64-v8a && mkdir -p $JNI_LIBS/armeabi-v7a
  cp target/aarch64-linux-android/release/libetopan.so $JNI_LIBS/arm64-v8a/libetopan.so
  cp target/armv7-linux-androideabi/release/libetopan.so $JNI_LIBS/armeabi-v7a/libetopan.so
  (cd etopan-app && ./gradlew clean && ./gradlew :app:bundleRelease && ./gradlew assemble)
  java -jar ~/.bundletool-all.jar build-bundle --modules=etopan-app/app/build/intermediates/module_bundle/release/out/base.zip --output=$OUT/etopa.aab
  jarsigner -keystore ~/.ltheinrich.jks -sigalg SHA256withRSA -digest-alg SHA-256 $OUT/etopa.aab etopa
  ~/.android/sdk/build-tools/30.0.2/zipalign -v -p 4 etopan-app/app/build/outputs/apk/release/app-release-unsigned.apk etopan-app/app/build/outputs/apk/release/app-release-unsigned-aligned.apk
  ~/.android/sdk/build-tools/30.0.2/apksigner sign --v4-signing-enabled false --ks ~/.ltheinrich.jks --ks-key-alias etopa --out $OUT/etopa.apk etopan-app/app/build/outputs/apk/release/app-release-unsigned-aligned.apk
elif [ $1 == "web" ]; then
  rm -f $OUT/etopa.tar.xz && rm -rf $OUT/ewm
  wasm-pack build --release --no-typescript -t web -d ../etopaw-app/pkg etopaw
  cp -r etopaw-app $OUT/ewm
  gominify -r -o $OUT/ewm/ etopaw-app/
  \cp etopaw-app/config.js $OUT/ewm/config.js
  (cd $OUT/ewm && tar cfJ ../etopa.tar.xz *)
  rm -rf $OUT/ewm
elif [ $1 == "full" ]; then
  ./build api
  ./build android # also runs ./build web
else
  echo "./build api|android|web|full"
fi
