#!/bin/bash

if [ "$#" -lt 1 ]; then
  echo "./run api|web|android|docker"
elif [ $1 == "api" ]; then
  cargo run -p etopai -- $@
elif [ $1 == "web" ]; then
  wasm-pack build --dev --no-typescript -t web -d ../etopaw-app/pkg etopaw
elif [ $1 == "android" ]; then
  JNI_LIBS=etopan-app/app/src/main/jniLibs
  if ! [[ "$PATH" == ?(*:)"$HOME/.android/ndk/arm64/bin"?(:*) ]]; then
    export PATH="$PATH:$HOME/.android/ndk/arm64/bin"
  fi
  cargo build -p etopan --target aarch64-linux-android
  rm -rf $JNI_LIBS && mkdir -p $JNI_LIBS/arm64-v8a
  cp target/aarch64-linux-android/debug/libetopan.so $JNI_LIBS/arm64-v8a/libetopan.so
else
  echo "./run api|web|android"
fi
