export const lang = {
    login: "Login",
    register: "Register",
    logout: "Logout",
    delete: "Delete",
    username: "Username",
    password: "Password",
    repeat_password: "Repeat password",
    name: "Name",
    secret: "Secret",
    add: "Add",
    new_password: "New password",
    repeat_new_password: "Repeat new password",
    user: "User",
    new_username: "New username",
    delete_user: "Delete user",
    key: "Key",
    decrypt: "Decrypt",
    change_username: "Change username",
    change_password: "Change password",
    change_key: "Change key",
    new_key: "New key",
    repeat_new_key: "Repeat new key",
    offline_mode: "Offline mode",
    disable_offline_mode: "Disable offline mode",
    add_secret: "Add secret",
    account: "Account",
    close: "Close",
    ok: "Ok",
    confirm: "Confirm",
    error: "Error",
    confirmation: "Confirmation",
    invalid_key: "Invalid key",
    empty_username_password: "Empty username or (encryption) password",
    username_changed: "Username successfully changed",
    password_changed: "Password successfully changed",
    key_changed: "Key successfully changed",
    empty_key: "Empty key",
    decryption_failed: "Could not decrypt secure storage",
    empty_storage: "Empty storage (offline mode unavailable)",
    delete_user_qm: "Delete user?",
    delete_secret_qm: "Delete secret \"$name\"?",
    api_error_cs: "API error: ",
    language: "Language",
    logout: "Logout",
    cancel: "Cancel",
    key_incorrect: "Key incorrect",
    passwords_no_match: "Passwords do not match",
    name_exists: "Name for secret already exists",
    name_secret_empty: "Name or secret empty",
    name_empty: "Name empty",
    name_nonexistent: "Name does not exist",
    unauthenticated: "Incorrect login credentials",
    invalid_secret: "Invalid secret",
    help: "Help",
    help_qa: {
        download: {
            q: "Download",
            a: "You can use an Etopa instance directly in your <a href=\"../\">browser</a> or in the <a href=\"https://play.google.com/store/apps/details?id=de.ltheinrich.etopa\">Android app</a>."
        },
        what_is: {
            q: "What is Etopa?",
            a: "Etopa is a time-based one-time password authenticator.<br>It was built with simplicity, data privacy and security in mind.<br>The Etopa web application or app generates 6-digit one-time login tokens for websites and services that support 2-factor-authentication (2FA)."
        },
        usage: {
            q: "How does it work?",
            a: "First you need to create an account (registration) with an unique username, a password and key that will be used for encrypting your data.<br>Second you enable 2FA for the service or website you want to use Etopa with.<br>Copy the given secret (e.g. JBSWY3DPEHPK3PXP) in combination with a chosen name into the add secret section on the bottom.<br>Once you have added the secret, you will be shown a different token every 30 seconds in the list.<br>Now you can use that token to login or verify your 2FA on the other website or service."
        },
        questions: {
            q: "Any questions?",
            a: "If you still have any questions or you have found a bug, please contact the developer via email <a href=\"mailto:lennart@ltheinrich.de\">lennart@ltheinrich.de</a> or create an <a href=\"https://ltheinrich.de/etopa/issues\">Issue on GitHub</a>."
        }
    },
    rename: "Rename",
    rename_secret_qm: "Rename secret \"$name\"?",
    new_name_for: "New name for \"$name\"",
    sure_to_delete: "Are you really sure to delete \"$name\"?",
    delete_timeout: "5s timeout to delete",
    edit: "Edit",
    edit_secret: "Edit secret",
    no_action_selected: "No action selected",
    repeat_secret_name: "Repeat secret name \"$name\"",
    repeat_name_incorrect: "Repeated name is incorrect",
    sure_to_rename_to: "Are you really sure to rename \"$name\" to \"$new_name\"?",
    source_code: "Source code",
    privacy_policy: "Privacy policy",
    incorrect_username: "Incorrect username"
};
