export const lang = {
    en: {
        login: "Login",
        register: "Register",
        logout: "Logout",
        delete: "Delete",
        username: "Username",
        password: "Password",
        repeat_password: "Repeat password",
        registration: "Registration",
        name: "Name",
        secret: "Secret",
        add: "Add",
        delete: "Delete",
        back: "Back",
        new_password: "New password",
        repeat_new_password: "Repeat new password",
        change_user: "Change user",
        user: "User",
        new_username: "New username",
        delete_user: "Delete user",
        key: "Key",
        decrypt: "Decrypt",
        encrypt: "Encrypt",
        change_username: "Change username",
        change_password: "Change password",
        change_key: "Change key",
        new_key: "New key",
        repeat_new_key: "Repeat new key",
        offline_mode: "Offline mode",
        disable_offline_mode: "Disable offline mode",
        add_secret: "Add secret",
        account: "Account",
        close: "Close",
        ok: "Ok",
        confirm: "Confirm",
        error: "Error",
        confirmation: "Confirmation",
        invalid_key: "Invalid key",
        empty_username_password: "Empty username or (encryption) password",
        username_changed: "Username successfully changed",
        password_changed: "Password successfully changed",
        key_changed: "Key successfully changed",
        empty_key: "Empty key",
        decryption_failed: "Could not decrypt secure storage",
        empty_storage: "Empty storage (offline mode unavailable)",
        delete_user_qm: "Delete user?",
        delete_secret_qm: "Delete secret?",
        api_error_cs: "API error: ",
        language: "Language",
        logout: "Logout",
        cancel: "Cancel",
        key_incorrect: "Key incorrect",
        passwords_no_match: "Passwords do not match",
        name_exists: "Name for secret already exists",
        name_secret_empty: "Name or secret empty",
        name_empty: "Name empty",
        name_nonexistent: "Name does not exist",
        unauthenticated: "Incorrect login credentials"
    },
    de: {
        // TODO german language
    }
};
