export const lang = {
    en: {
        login: "Login",
        register: "Register",
        logout: "Logout",
        delete: "Delete",
        username: "Username",
        password: "Password",
        repeat_password: "Repeat password",
        name: "Name",
        secret: "Secret",
        add: "Add",
        new_password: "New password",
        repeat_new_password: "Repeat new password",
        user: "User",
        new_username: "New username",
        delete_user: "Delete user",
        key: "Key",
        decrypt: "Decrypt",
        change_username: "Change username",
        change_password: "Change password",
        change_key: "Change key",
        new_key: "New key",
        repeat_new_key: "Repeat new key",
        offline_mode: "Offline mode",
        disable_offline_mode: "Disable offline mode",
        add_secret: "Add secret",
        account: "Account",
        close: "Close",
        ok: "Ok",
        confirm: "Confirm",
        error: "Error",
        confirmation: "Confirmation",
        invalid_key: "Invalid key",
        empty_username_password: "Empty username or (encryption) password",
        username_changed: "Username successfully changed",
        password_changed: "Password successfully changed",
        key_changed: "Key successfully changed",
        empty_key: "Empty key",
        decryption_failed: "Could not decrypt secure storage",
        empty_storage: "Empty storage (offline mode unavailable)",
        delete_user_qm: "Delete user?",
        delete_secret_qm: "Delete secret?",
        api_error_cs: "API error: ",
        language: "Language",
        logout: "Logout",
        cancel: "Cancel",
        key_incorrect: "Key incorrect",
        passwords_no_match: "Passwords do not match",
        name_exists: "Name for secret already exists",
        name_secret_empty: "Name or secret empty",
        name_empty: "Name empty",
        name_nonexistent: "Name does not exist",
        unauthenticated: "Incorrect login credentials",
        invalid_secret: "Invalid secret"
    },
    de: {
        login: "Anmelden",
        register: "Registrieren",
        logout: "Abmelden",
        delete: "Löschen",
        username: "Benutzername",
        password: "Passwort",
        repeat_password: "Passwort wiederholen",
        name: "Name",
        secret: "Geheimnis",
        add: "Hinzufügen",
        new_password: "Neues Passwort",
        repeat_new_password: "Neues Passwort wiederholen",
        new_username: "Neuer Benutzername",
        delete_user: "Benutzer löschen",
        key: "Schlüssel",
        decrypt: "Entschlüsseln",
        change_username: "Benutzernamen ändern",
        change_password: "Passwort ändern",
        change_key: "Schlüssel ändern",
        new_key: "Neuer Schlüssel",
        repeat_new_key: "Neuen Schlüssel wiederholen",
        offline_mode: "Offline-Modus",
        disable_offline_mode: "Offline-Modus deaktivieren",
        add_secret: "Geheimnis hinzufügen",
        account: "Account",
        close: "Schließen",
        ok: "Ok",
        confirm: "Bestätigen",
        error: "Fehler",
        confirmation: "Bestätigung",
        invalid_key: "Ungültiger Schlüssel",
        empty_username_password: "Leerer Benutzername oder Passwort",
        username_changed: "Benutzername erfolgreich geändert",
        password_changed: "Passwort erfolgreich geändert",
        key_changed: "Schlüssel erfolgreich geändert",
        empty_key: "Leerer Schlüssel",
        decryption_failed: "Sicherer Speicher konnte nicht entschlüsselt werden",
        empty_storage: "Leerer Speicher (Offline-Modus nicht verfügbar)",
        delete_user_qm: "Benutzer wirklich löschen?",
        delete_secret_qm: "Geheimnis wirklich löschen?",
        api_error_cs: "Server/API Fehler: ",
        language: "Sprache",
        logout: "Abmelden",
        cancel: "Abbrechen",
        key_incorrect: "Schlüssel ungültig",
        passwords_no_match: "Passwörter stimmen nicht überein",
        name_exists: "Name des Geheimnisses existiert bereit",
        name_secret_empty: "Leerer Name oder Geheimnis",
        name_empty: "Leerer Name",
        name_nonexistent: "Name existiert nicht",
        unauthenticated: "Ungültige Anmeldedaten",
        invalid_secret: "Ungültiges Geheimnis"
    }
};
