export const lang = {
    login: "Zaloguj",
    register: "Rejestracja",
    logout: "Wyloguj",
    delete: "Usuń",
    username: "Nazwa użytkownika",
    password: "Hasło",
    repeat_password: "Powtórz hasło",
    name: "Nazwa",
    secret: "Sekret",
    add: "Dodaj",
    new_password: "Nowe hasło",
    repeat_new_password: "Powtórz nowe hasło",
    user: "Użytkownik",
    new_username: "Nowa nazwa użytkownika",
    delete_user: "Usuń użytkownika",
    key: "Klucz",
    decrypt: "Odszyfruj",
    change_username: "Zmień nazwę użytkownika",
    change_password: "Zmień hasło",
    change_key: "Zmień klucz",
    new_key: "Nowy klucz",
    repeat_new_key: "Powtórz nowy klucz",
    offline_mode: "Offline mode",
    disable_offline_mode: "Wyłącz offline mode",
    add_secret: "Dodaj sekret",
    account: "Konto",
    close: "Zamknij",
    ok: "Ok",
    confirm: "Potwierdź",
    error: "Błąd",
    confirmation: "Potwierdzenie",
    invalid_key: "Błędny klucz",
    empty_username_password: "Pusta nazwa użytkownika lub hasło (szyfrowania)",
    username_changed: "Nazwa użytkownika zmieniona",
    password_changed: "Hasło zostało zmienione",
    key_changed: "Klucz został zmieniony",
    empty_key: "Pusty klucz",
    decryption_failed: "Nie można odszyfrować bezpiecznego sejfu",
    empty_storage: "Pusty magazyn (tryb offline niedostępny)",
    delete_user_qm: "Usunąć użytkownika?",
    delete_secret_qm: "Usunąć sekret \"$name\"?",
    api_error_cs: "API error: ",
    language: "Język",
    logout: "Wyloguj",
    cancel: "Anuluj",
    key_incorrect: "Błędny klucz",
    passwords_no_match: "Błędne hasło",
    name_exists: "Nazwa sekretu istnieje",
    name_secret_empty: "Nazwa lub sekret pusty",
    name_empty: "Pusta nazwa",
    name_nonexistent: "Nazwa nie istnieje",
    unauthenticated: "Nieprawidłowe dane logowania",
    invalid_secret: "Błędny sekret",
    help: "Pomoc",
    help_qa: {
        download: {
            q: "Pobierz",
            a: "You can use an Etopa instance directly in your <a href=\"../\">browser</a> or in the <a href=\"https://play.google.com/store/apps/details?id=de.ltheinrich.etopa\">Android app</a>."
        },
        what_is: {
            q: "What is Etopa?",
            a: "Etopa is a time-based one-time password authenticator.<br>It was built with simplicity, data privacy and security in mind.<br>The Etopa web application or app generates 6-digit one-time login tokens for websites and services that support 2-factor-authentication (2FA)."
        },
        usage: {
            q: "How does it work?",
            a: "First you need to create an account (registration) with an unique username, a password and key that will be used for encrypting your data.<br>Second you enable 2FA for the service or website you want to use Etopa with.<br>Copy the given secret (e.g. JBSWY3DPEHPK3PXP) in combination with a chosen name into the add secret section on the bottom.<br>Once you have added the secret, you will be shown a different token every 30 seconds in the list.<br>Now you can use that token to login or verify your 2FA on the other website or service."
        },
        questions: {
            q: "Any questions?",
            a: "If you still have any questions or you have found a bug, please contact the developer via email <a href=\"mailto:lennart@ltheinrich.de\">lennart@ltheinrich.de</a> or create an <a href=\"https://ltheinrich.de/etopa/issues\">Issue on GitHub</a>."
        }
    },
    rename: "Zmień nazwę",
    rename_secret_qm: "Zmienić nazwę sekretu \"$name\"?",
    new_name_for: "Nowa nazwa dla \"$name\"",
    sure_to_delete: "Napewno chcesz usunąć \"$name\"?",
    delete_timeout: "5s do usunięcia",
    edit: "Edytuj",
    edit_secret: "Edytuj sekret",
    no_action_selected: "Brak akcji",
    repeat_secret_name: "Powtórz nazwę sekretu \"$name\"",
    repeat_name_incorrect: "Nazwa sekretu nie pasuje",
    sure_to_rename_to: "Napewno chcesz zmienić nazwę \"$name\" na \"$new_name\"?",
    source_code: "Kod źródłowy",
    privacy_policy: "Polityka prywatności",
    incorrect_username: "Błędna nazwa użytkownika",
    username_not_alphanumeric: "Nazwa użytkownika nie jest alfanumeryczna",
    export_database: "Eksportuj bazę danych",
    import_database: "Importuj bazę danych",
    import_overwrites_database: "Importowanie powoduje nadpisanie bieżącej bazy danych, a istniejące dane zostaną nieodwracalnie utracone!",
    import_database_qm: "Importować bazę danych?",
    no_file_selected: "Nie wybrano pliku",
    database_imported: "Baza danych zaimportowana",
    import_key: "Importuj klucz",
    invalid_import_key: "Importowany klucz jest błędny"
};
