export const lang = {
    login: "Войти",
    register: "Регистрация",
    logout: "Выйти",
    delete: "Удалить",
    username: "Имя пользователь",
    password: "Пароль",
    repeat_password: "Повторить пороль",
    name: "Имя",
    secret: "Секрет",
    add: "Добавить",
    new_password: "Новий пароль",
    repeat_new_password: "Повторите новый пароль",
    user: "пользаватель",
    new_username: "Новый пользаватель",
    delete_user: "Удалить пользавателя",
    key: "Ключ",
    decrypt: "Разшифровать",
    change_username: "Изменить имя пользователя",
    change_password: "Изменить пароль",
    change_key: "Изменить ключ",
    new_key: "Новый ключ",
    repeat_new_key: "Повторите новый ключ",
    offline_mode: "Автономный режим",
    disable_offline_mode: "Выйти из автономного режима",
    add_secret: "Добавить секрет",
    account: "Аккаунт",
    close: "Закрыть",
    ok: "Ок",
    confirm: "Подтвердить",
    error: "Ошибка",
    confirmation: "Подтверждение",
    invalid_key: "Неверный ключ",
    empty_username_password: "Пустое поле пользавателя или пароля",
    username_changed: "Имя пользавателя успешно изменено",
    password_changed: "Пароль успешно изменен",
    key_changed: "Schlüssel erfolgreich geändert",
    empty_key: "Пустой ключ",
    decryption_failed: "Ошибка при разшифрофки",
    empty_storage: "Автономный режим недоступен",
    delete_user_qm: "Подтвердить удаление пользавателя",
    delete_secret_qm: "Удалить секрет \"$name\"",
    api_error_cs: "Server/API Ошибка: ",
    language: "Язык",
    logout: "Выйти",
    cancel: "Отменить",
    key_incorrect: "Неверный ключ",
    passwords_no_match: "Неправельный повтор пароля",
    name_exists: "Название секрета уже существует",
    name_secret_empty: "Пустое название секрета",
    name_empty: "Leerer Name",
    name_nonexistent: "Название не существует",
    unauthenticated: "Неверные данные",
    invalid_secret: "Неверный секрет",
    help: "Помощь",
    help_qa: {
        download: {
            q: "Скачать",
            a: "Вы можете использовать Etopa прямо в <a href=\"../\">браузере</a> или в <a href=\"https://play.google.com/store/apps/details?id=de.ltheinrich.etopa\">аппликация для Android</a>"
        },
        what_is: {
            q: "Что Etopa?",
            a: "Etopa - это аппликация для аутентификации с использованием одноразового пароля на основе времени.<br>Он был разработан с учетом простоты, конфиденциальности и безопасности.<br>Веб-аппликация Etopa или аппликация для Android генерирует одноразовые пароли (токены) из 6 цифр для входа на веб-сайты и в сервисы, поддерживающие двухфакторную аутентификацию (2FA)."
        },
        usage: {
            q: "Как работает Etopa?",
            a: "Сначала вам нужно создать учетную запись пользователя с уникальным именем пользователя, паролем и ключом.<br>Выбранный ключ используется для шифрования данных.<br>Затем вы активируете 2FA на сервисе или веб-сайте, который хотите использовать с Etopa.<br>Теперь вы должны ввести сгенерированный / полученный секрет (например, JBSWY3DPEHPK3PXP) вместе со свободно выбранным именем в форме после регистрации и добавить его.<br>Как только секрет был добавлен, новый одноразовый пароль (токен) генерируется в списке каждые 30 секунд.<br>Этот одноразовый пароль теперь можно использовать для входа в систему или для проверки другой службы или веб-сайта."
        },
        questions: {
            q: "Еще вопросы?",
            a: "Если у вас все еще есть вопросы или вы обнаружили ошибку, свяжитесь с разработчиком по электронной почте <a href=\"mailto:lennart@ltheinrich.de\">lennart@ltheinrich.de</a> или с <a href=\"https://ltheinrich.de/etopa/issues\">проблемой на GitHub</a>."
        }
    },
    rename: "Переиминовать",
    rename_secret_qm: "Переиминовать секрет \"$name\" umbenennen?",
    new_name_for: "Новое название для \"$name\"",
    sure_to_delete: "Уверенны удалить секрет \"$name\"?",
    delete_timeout: "5s Timeout для удаления",
    edit: "Редактировать",
    edit_secret: "Редактировать секрет",
    no_action_selected: "Действие не выбранно",
    repeat_secret_name: "Повторить название секрета \"$name\"",
    repeat_name_incorrect: "Неверный повтор имени",
    sure_to_rename_to: "Секрет точно переиминовать в \"$name\" \"$new_name\"?",
    source_code: "Исходный текст",
    privacy_policy: "Декларация о защите данных",
    incorrect_username: "Неправильное имя пользователя",
    username_not_alphanumeric: "Имя пользователя не буквенно-цифровое",
    export_database: "Экспорт базы данных",
    import_database: "импорт базы данных",
    import_overwrites_database: "При импорте предыдущая база данных затирается, а существующие данные безвозвратно теряются!",
    import_database_qm: "Действительно импортировать базу данных?",
    no_file_selected: "Файл не выбран",
    database_imported: "База данных успешно импортирована",
    import_key: "ключ импорта",
    invalid_import_key: "Недействительный ключ импорта"
};
